import type { QuizQuestion } from '../types';

export const d1IpAddressingQuiz: QuizQuestion[] = [
  {
    id: 'd1ip-q1',
    type: 'single-mcq',
    stem: 'How many bits are in an IPv4 address?',
    options: [
      { id: 'a', text: '16' },
      { id: 'b', text: '32' },
      { id: 'c', text: '48' },
      { id: 'd', text: '128' },
    ],
    correct: 'b',
    explanation: 'IPv4 addresses are 32 bits long, organized into 4 octets of 8 bits each, written in dotted decimal notation (e.g., 192.168.1.1). Each octet can hold a value from 0 to 255.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q2',
    type: 'true-false',
    stem: 'The address 172.32.0.1 is a valid RFC 1918 private IP address.',
    correct: 'false',
    explanation: 'The RFC 1918 private range for Class B is 172.16.0.0/12, which covers 172.16.0.0 through 172.31.255.255. The address 172.32.0.1 falls outside this range and is a public address. This is a classic exam trap.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q3',
    type: 'single-mcq',
    stem: 'What is the correctly compressed form of the IPv6 address 2001:0db8:0000:0000:0000:0000:0000:0001?',
    options: [
      { id: 'a', text: '2001:db8::1' },
      { id: 'b', text: '2001:db8:0:0:0:0:0:1' },
      { id: 'c', text: '2001:db8:::1' },
      { id: 'd', text: '2001:db8:1::' },
    ],
    correct: 'a',
    explanation: 'Leading zeros in each group can be dropped (0db8 becomes db8, 0001 becomes 1). One consecutive run of all-zero groups can be replaced with ::. Only one :: is allowed per address. The result is 2001:db8::1.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q4',
    type: 'multi-mcq',
    stem: 'Which of the following are RFC 1918 private address ranges? (Select all that apply)',
    options: [
      { id: 'a', text: '10.0.0.0/8' },
      { id: 'b', text: '172.16.0.0/12' },
      { id: 'c', text: '192.168.0.0/16' },
      { id: 'd', text: '169.254.0.0/16' },
    ],
    correct: ['a', 'b', 'c'],
    explanation: 'RFC 1918 defines three private ranges: 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. The 169.254.0.0/16 range is the IPv4 link-local (APIPA) range, not an RFC 1918 private range.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q5',
    type: 'fill-blank',
    stem: 'The first 24 bits of a MAC address are called the ___, which identifies the manufacturer.',
    correct: 'OUI',
    explanation: 'The OUI (Organizationally Unique Identifier) is the first 24 bits of a MAC address, assigned by IEEE to each manufacturer. The remaining 24 bits are assigned by the manufacturer to uniquely identify each network interface card.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q6',
    type: 'single-mcq',
    stem: 'What does an IPv4 address starting with 169.254 indicate?',
    options: [
      { id: 'a', text: 'The device has a static IP configuration' },
      { id: 'b', text: 'The device obtained an address via DHCP' },
      { id: 'c', text: 'DHCP failed and the device assigned itself a link-local address' },
      { id: 'd', text: 'The device is using NAT' },
    ],
    correct: 'c',
    explanation: 'An address in the 169.254.0.0/16 range is an APIPA (Automatic Private IP Addressing) or link-local address. It is automatically assigned when a device cannot reach a DHCP server. This is a key troubleshooting indicator — if you see 169.254.x.x, DHCP has failed.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q7',
    type: 'true-false',
    stem: 'IPv6 uses broadcast addresses just like IPv4.',
    correct: 'false',
    explanation: 'IPv6 does not have broadcast. Instead, it uses multicast to reach multiple devices. The IPv6 multicast address range starts with ff00::/8. This is one of the key architectural differences between IPv4 and IPv6.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q8',
    type: 'single-mcq',
    stem: 'Which IPv6 address is the loopback address?',
    options: [
      { id: 'a', text: 'fe80::1' },
      { id: 'b', text: '::1' },
      { id: 'c', text: 'ff02::1' },
      { id: 'd', text: '2001:db8::1' },
    ],
    correct: 'b',
    explanation: '::1 is the IPv6 loopback address, equivalent to 127.0.0.1 in IPv4. Traffic sent to ::1 never leaves the device. fe80::/10 is the link-local range, ff02::1 is the all-nodes multicast address, and 2001:db8::/32 is the documentation prefix.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q9',
    type: 'multi-mcq',
    stem: 'Which statements about dual-stack are correct? (Select all that apply)',
    options: [
      { id: 'a', text: 'Devices run both IPv4 and IPv6 protocol stacks simultaneously' },
      { id: 'b', text: 'Every interface has both an IPv4 and an IPv6 address' },
      { id: 'c', text: 'It encapsulates IPv6 inside IPv4 packets' },
      { id: 'd', text: 'The device chooses which protocol to use based on the destination' },
    ],
    correct: ['a', 'b', 'd'],
    explanation: 'Dual-stack means both IPv4 and IPv6 run simultaneously on the same device, with each interface having addresses for both protocols. The device selects the appropriate protocol based on the destination. Encapsulation of IPv6 inside IPv4 is tunneling, not dual-stack.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1ip-q10',
    type: 'fill-blank',
    stem: 'In a MAC address, if the least significant bit of the first octet is 1, the address is a ___ address.',
    correct: 'multicast',
    explanation: 'The LSB (least significant bit) of the first octet of a MAC address indicates the address type: 0 = unicast (one specific device), 1 = multicast (a group of devices). For example, 01:00:5E:xx:xx:xx is the IPv4 multicast MAC range because the first octet (01) has LSB = 1.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
];
