import type { QuizQuestion } from '../types';

export const d1NetworkComponentsQuiz: QuizQuestion[] = [
  {
    id: 'd1nc-q1',
    type: 'single-mcq',
    stem: 'Which device forwards packets based on IP addresses?',
    options: [
      { id: 'a', text: 'Switch' },
      { id: 'b', text: 'Router' },
      { id: 'c', text: 'Hub' },
      { id: 'd', text: 'Wireless access point' },
    ],
    correct: 'b',
    explanation: 'Routers operate at Layer 3 (Network layer) and make forwarding decisions based on destination IP addresses. Switches use MAC addresses (Layer 2), hubs broadcast to all ports (Layer 1), and WAPs bridge wireless to wired (Layer 1-2).',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q2',
    type: 'true-false',
    stem: 'End devices forward traffic for other devices on the network.',
    correct: 'false',
    explanation: 'End devices (hosts) only send and receive their own traffic. They do not make forwarding decisions for other devices. That is the role of intermediary devices like routers and switches.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q3',
    type: 'single-mcq',
    stem: 'What is the maximum recommended segment length for Cat6 copper Ethernet cable?',
    options: [
      { id: 'a', text: '50 meters' },
      { id: 'b', text: '100 meters' },
      { id: 'c', text: '200 meters' },
      { id: 'd', text: '500 meters' },
    ],
    correct: 'b',
    explanation: 'The Ethernet standard limits copper twisted-pair cable segments to 100 meters. Beyond this distance, signal degradation becomes unreliable. Fiber optic cable is used for longer runs.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q4',
    type: 'multi-mcq',
    stem: 'Which of the following are types of network media? (Select all that apply)',
    options: [
      { id: 'a', text: 'Copper cable' },
      { id: 'b', text: 'Fiber optic cable' },
      { id: 'c', text: 'Wireless (radio waves)' },
      { id: 'd', text: 'Routing tables' },
    ],
    correct: ['a', 'b', 'c'],
    explanation: 'Network media refers to the physical path signals travel along: copper cable (electrical signals), fiber optic (light signals), and wireless (radio waves). Routing tables are logical structures, not physical media.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q5',
    type: 'single-mcq',
    stem: 'In the postal system analogy, what do routers represent?',
    options: [
      { id: 'a', text: 'Houses' },
      { id: 'b', text: 'Local post offices' },
      { id: 'c', text: 'Regional distribution centers' },
      { id: 'd', text: 'Roads' },
    ],
    correct: 'c',
    explanation: 'In the analogy: houses = end devices, local post offices = switches (sort by street address/MAC), regional distribution centers = routers (decide which city/ZIP code/IP network), and roads = cables/media.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q6',
    type: 'fill-blank',
    stem: 'A switch operates primarily at Layer ___ of the OSI model.',
    correct: '2',
    explanation: 'Switches operate at Layer 2 (Data Link layer) and forward frames based on MAC addresses. Some multilayer switches also operate at Layer 3, but the standard CCNA definition places switches at Layer 2.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q7',
    type: 'true-false',
    stem: 'In a star topology, if one cable fails, only the device connected to that cable loses connectivity.',
    correct: 'true',
    explanation: 'Star topology connects every device to a central switch. Each connection is independent, so a single cable failure only affects that one device. This is why star topology is the most common in modern networks.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q8',
    type: 'single-mcq',
    stem: 'What does the "show version" command reveal on a Cisco device?',
    options: [
      { id: 'a', text: 'Only the IP address configuration' },
      { id: 'b', text: 'Device model, IOS version, uptime, and memory' },
      { id: 'c', text: 'The routing table' },
      { id: 'd', text: 'Connected neighbors' },
    ],
    correct: 'b',
    explanation: '"show version" is the first command you should run on any Cisco device. It displays the device model, IOS version, uptime, memory, and other hardware details. The routing table uses "show ip route" and neighbors use "show cdp neighbors".',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q9',
    type: 'multi-mcq',
    stem: 'Which statements about wireless as network media are correct? (Select all that apply)',
    options: [
      { id: 'a', text: 'It uses radio waves to carry data' },
      { id: 'b', text: 'Every device on the same channel competes for airtime' },
      { id: 'c', text: 'It uses IEEE 802.11 standards' },
      { id: 'd', text: 'Each device gets its own dedicated collision domain' },
    ],
    correct: ['a', 'b', 'c'],
    explanation: 'Wireless uses radio waves (802.11 standards) and is shared media — all devices on the same channel compete for airtime. This is different from switched Ethernet where each port is its own collision domain.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1nc-q10',
    type: 'fill-blank',
    stem: 'A router connects different ___ together.',
    correct: 'networks',
    explanation: 'Routers connect different networks together and make forwarding decisions between them. Switches connect devices within the same network. This fundamental distinction is tested constantly on the CCNA exam.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
];
