import type { QuizQuestion } from '../types';

export const d1OsiModelQuiz: QuizQuestion[] = [
  {
    id: 'd1osi-q1',
    type: 'single-mcq',
    stem: 'Which OSI layer is responsible for logical addressing and routing?',
    options: [
      { id: 'a', text: 'Data Link layer' },
      { id: 'b', text: 'Network layer' },
      { id: 'c', text: 'Transport layer' },
      { id: 'd', text: 'Session layer' },
    ],
    correct: 'b',
    explanation: 'The Network layer (Layer 3) handles logical addressing (IP addresses) and routing decisions. The Data Link layer handles physical addressing (MAC), Transport handles end-to-end delivery, and Session manages connections between applications.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q2',
    type: 'true-false',
    stem: 'The OSI model has 7 layers and the TCP/IP model has 4 layers.',
    correct: 'true',
    explanation: 'The OSI model has 7 layers (Physical, Data Link, Network, Transport, Session, Presentation, Application). The TCP/IP model has 4 layers (Network Access, Internet, Transport, Application). Both models serve as frameworks for understanding network communication.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q3',
    type: 'single-mcq',
    stem: 'What is the PDU (Protocol Data Unit) called at the Transport layer?',
    options: [
      { id: 'a', text: 'Frame' },
      { id: 'b', text: 'Packet' },
      { id: 'c', text: 'Segment' },
      { id: 'd', text: 'Bit' },
    ],
    correct: 'c',
    explanation: 'At the Transport layer, the PDU is called a segment. At the Network layer it is a packet, at the Data Link layer it is a frame, and at the Physical layer it is a bit. Knowing PDU names per layer is essential for the CCNA exam.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q4',
    type: 'multi-mcq',
    stem: 'Which of the following are Layer 2 (Data Link layer) protocols or concepts? (Select all that apply)',
    options: [
      { id: 'a', text: 'MAC addresses' },
      { id: 'b', text: 'Ethernet' },
      { id: 'c', text: 'IP addresses' },
      { id: 'd', text: 'Switches' },
    ],
    correct: ['a', 'b', 'd'],
    explanation: 'MAC addresses, Ethernet, and switches all operate at Layer 2 (Data Link). IP addresses operate at Layer 3 (Network). The Data Link layer handles frame delivery within the same network segment.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q5',
    type: 'fill-blank',
    stem: 'Encapsulation is the process of adding headers (and sometimes trailers) to data as it moves ___ the OSI model layers.',
    correct: 'down',
    explanation: 'Encapsulation adds headers as data moves down the OSI model (from Application to Physical). Decapsulation removes headers as data moves up the model at the receiving end. Think of it like putting a letter in envelopes within envelopes.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q6',
    type: 'single-mcq',
    stem: 'Which TCP/IP model layer combines the OSI Session, Presentation, and Application layers?',
    options: [
      { id: 'a', text: 'Network Access' },
      { id: 'b', text: 'Internet' },
      { id: 'c', text: 'Transport' },
      { id: 'd', text: 'Application' },
    ],
    correct: 'd',
    explanation: 'The TCP/IP Application layer combines the top three OSI layers: Session (layer 5), Presentation (layer 6), and Application (layer 7). This is why protocols like HTTP, DNS, and DHCP all map to the TCP/IP Application layer.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q7',
    type: 'true-false',
    stem: 'A switch operates at the Physical layer of the OSI model.',
    correct: 'false',
    explanation: 'A standard switch operates at Layer 2 (Data Link layer), making forwarding decisions based on MAC addresses. Hubs operate at Layer 1 (Physical layer). Multilayer switches can also operate at Layer 3.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q8',
    type: 'multi-mcq',
    stem: 'Which protocols operate at the Transport layer? (Select all that apply)',
    options: [
      { id: 'a', text: 'TCP' },
      { id: 'b', text: 'UDP' },
      { id: 'c', text: 'IP' },
      { id: 'd', text: 'HTTP' },
    ],
    correct: ['a', 'b'],
    explanation: 'TCP and UDP are Transport layer (Layer 4) protocols. TCP provides reliable, connection-oriented delivery. UDP provides fast, connectionless delivery. IP is a Network layer protocol, and HTTP is an Application layer protocol.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q9',
    type: 'single-mcq',
    stem: 'What is the primary purpose of the OSI model?',
    options: [
      { id: 'a', text: 'To define specific network hardware' },
      { id: 'b', text: 'To provide a common framework for understanding network communication' },
      { id: 'c', text: 'To replace the TCP/IP model' },
      { id: 'd', text: 'To configure routers and switches' },
    ],
    correct: 'b',
    explanation: 'The OSI model is a conceptual framework — it does not define specific hardware or replace TCP/IP. It provides a common language for understanding how data moves through a network, which helps with troubleshooting and protocol design.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1osi-q10',
    type: 'fill-blank',
    stem: 'The correct order of encapsulation from top to bottom is: Data → Segment → Packet → ___ → Bits.',
    correct: 'frame',
    explanation: 'The encapsulation order from Application layer down is: Data (L7) → Segment (L4) → Packet (L3) → Frame (L2) → Bits (L1). Each layer adds its own header (and sometimes trailer) to the data it receives from the layer above.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
];
