import type { QuizQuestion } from '../types';

export const d1SubnettingBasicsQuiz: QuizQuestion[] = [
  {
    id: 'd1sb-q1',
    type: 'single-mcq',
    stem: 'How many usable host addresses does a /27 subnet provide?',
    options: [
      { id: 'a', text: '14' },
      { id: 'b', text: '30' },
      { id: 'c', text: '32' },
      { id: 'd', text: '62' },
    ],
    correct: 'b',
    explanation: 'A /27 has 5 host bits (32 - 27 = 5). Hosts = 2^5 - 2 = 32 - 2 = 30 usable addresses. The -2 removes the network address (all host bits = 0) and the broadcast address (all host bits = 1).',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q2',
    type: 'true-false',
    stem: 'The network address of a subnet can be assigned to a host device.',
    correct: 'false',
    explanation: 'The network address (all host bits = 0) identifies the subnet itself and cannot be assigned to any individual host. Similarly, the broadcast address (all host bits = 1) cannot be assigned. Only addresses between these two boundaries are usable.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q3',
    type: 'single-mcq',
    stem: 'What is the subnet mask for a /28 network?',
    options: [
      { id: 'a', text: '255.255.255.192' },
      { id: 'b', text: '255.255.255.224' },
      { id: 'c', text: '255.255.255.240' },
      { id: 'd', text: '255.255.255.248' },
    ],
    correct: 'c',
    explanation: '/28 means 28 network bits and 4 host bits. The 4th octet has 4 bits set to 1: 11110000 = 128 + 64 + 32 + 16 = 240. So the mask is 255.255.255.240.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q4',
    type: 'multi-mcq',
    stem: 'Which of the following are valid host addresses in the 192.168.1.0/26 subnet? (Select all that apply)',
    options: [
      { id: 'a', text: '192.168.1.0' },
      { id: 'b', text: '192.168.1.1' },
      { id: 'c', text: '192.168.1.62' },
      { id: 'd', text: '192.168.1.63' },
    ],
    correct: ['b', 'c'],
    explanation: 'A /26 has a block size of 64. The network address is 192.168.1.0 (not assignable) and the broadcast is 192.168.1.63 (not assignable). Usable hosts range from 192.168.1.1 through 192.168.1.62.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q5',
    type: 'fill-blank',
    stem: 'The block size for a subnet with mask 255.255.255.224 is ___.',
    correct: '32',
    explanation: 'Block size = 256 - interesting octet value. For mask 255.255.255.224, the interesting octet is 224. Block size = 256 - 224 = 32. Subnets increment by 32: .0, .32, .64, .96, .128, .160, .192, .224.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q6',
    type: 'single-mcq',
    stem: 'You need to create at least 6 subnets from a /24 network. What is the minimum CIDR you must use?',
    options: [
      { id: 'a', text: '/25' },
      { id: 'b', text: '/26' },
      { id: 'c', text: '/27' },
      { id: 'd', text: '/28' },
    ],
    correct: 'c',
    explanation: 'Number of subnets = 2^(borrowed bits). To get at least 6 subnets: 2^3 = 8 subnets (3 borrowed bits). New CIDR = 24 + 3 = /27. A /25 gives only 2 subnets and /26 gives only 4 subnets.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q7',
    type: 'true-false',
    stem: 'When using VLSM, you should always allocate the smallest subnets first.',
    correct: 'false',
    explanation: 'With VLSM, you must always allocate the largest subnets first. Starting with the smallest subnets fragments the address space and may leave no contiguous block large enough for the bigger subnets. This is a fundamental VLSM rule tested on the CCNA.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q8',
    type: 'single-mcq',
    stem: 'What is the broadcast address for the subnet 10.0.0.0/29?',
    options: [
      { id: 'a', text: '10.0.0.7' },
      { id: 'b', text: '10.0.0.8' },
      { id: 'c', text: '10.0.0.15' },
      { id: 'd', text: '10.0.0.255' },
    ],
    correct: 'a',
    explanation: 'A /29 has 3 host bits. Block size = 2^3 = 8. The first subnet is 10.0.0.0/29 with range 10.0.0.0 through 10.0.0.7. The broadcast address is the last address in the range: 10.0.0.7.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q9',
    type: 'multi-mcq',
    stem: 'Which statements about a /30 subnet are correct? (Select all that apply)',
    options: [
      { id: 'a', text: 'It provides exactly 2 usable host addresses' },
      { id: 'b', text: 'It is commonly used for point-to-point links' },
      { id: 'c', text: 'The subnet mask is 255.255.255.252' },
      { id: 'd', text: 'It provides 4 usable host addresses' },
    ],
    correct: ['a', 'b', 'c'],
    explanation: 'A /30 has 2 host bits: 2^2 - 2 = 2 usable hosts. The mask is 255.255.255.252 (11111100 in the last octet). It is the standard choice for point-to-point serial links because those links connect exactly two router interfaces.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1sb-q10',
    type: 'fill-blank',
    stem: 'To satisfy a requirement of 50 hosts per subnet, the minimum number of host bits needed is ___.',
    correct: '6',
    explanation: 'We need 2^h - 2 ≥ 50. Testing: 2^5 - 2 = 30 (too few), 2^6 - 2 = 62 (enough). So we need 6 host bits. For a /24 starting point, the new CIDR would be 32 - 6 = /26.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
];
