import type { QuizQuestion } from '../types';

// Domain 1 quiz: 30 questions drawn from all Domain 1 lessons
export const domain1Quiz: QuizQuestion[] = [
  // --- Network Components (10 questions) ---
  {
    id: 'd1dq-1',
    type: 'single-mcq',
    stem: 'Which device connects different networks and forwards packets based on IP addresses?',
    options: [
      { id: 'a', text: 'Hub' },
      { id: 'b', text: 'Switch' },
      { id: 'c', text: 'Router' },
      { id: 'd', text: 'Bridge' },
    ],
    correct: 'c',
    explanation: 'Routers operate at Layer 3 and connect different networks using IP-based forwarding decisions.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-2',
    type: 'true-false',
    stem: 'A hub forwards frames only to the port where the destination MAC address is located.',
    correct: 'false',
    explanation: 'A hub broadcasts incoming data to all ports (Layer 1). A switch forwards frames to specific ports based on MAC addresses (Layer 2).',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-3',
    type: 'single-mcq',
    stem: 'What connector type is used for Cat6 Ethernet cable?',
    options: [
      { id: 'a', text: 'RJ-11' },
      { id: 'b', text: 'RJ-45' },
      { id: 'c', text: 'LC' },
      { id: 'd', text: 'BNC' },
    ],
    correct: 'b',
    explanation: 'RJ-45 is the standard connector for twisted-pair Ethernet cable (Cat5e, Cat6). RJ-11 is for telephone, LC is for fiber, and BNC is for coaxial.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-4',
    type: 'multi-mcq',
    stem: 'Which of the following are intermediary network devices? (Select all that apply)',
    options: [
      { id: 'a', text: 'Router' },
      { id: 'b', text: 'Printer' },
      { id: 'c', text: 'Switch' },
      { id: 'd', text: 'Wireless access point' },
    ],
    correct: ['a', 'c', 'd'],
    explanation: 'Routers, switches, and wireless access points are intermediary devices that forward traffic for other devices. A printer is an end device (host).',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-5',
    type: 'fill-blank',
    stem: 'The most common physical network topology in modern networks is the ___ topology.',
    correct: 'star',
    explanation: 'Star topology connects every device to a central switch. It is the most common because a single cable failure only affects one device.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  // --- OSI Model (8 questions) ---
  {
    id: 'd1dq-6',
    type: 'single-mcq',
    stem: 'At which OSI layer does a router primarily operate?',
    options: [
      { id: 'a', text: 'Layer 1' },
      { id: 'b', text: 'Layer 2' },
      { id: 'c', text: 'Layer 3' },
      { id: 'd', text: 'Layer 4' },
    ],
    correct: 'c',
    explanation: 'Routers operate at Layer 3 (Network layer), making forwarding decisions based on IP addresses.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-7',
    type: 'true-false',
    stem: 'The TCP/IP model has more layers than the OSI model.',
    correct: 'false',
    explanation: 'The TCP/IP model has 4 layers while the OSI model has 7 layers. TCP/IP combines the top three OSI layers into a single Application layer.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-8',
    type: 'single-mcq',
    stem: 'What is the PDU at the Data Link layer?',
    options: [
      { id: 'a', text: 'Bit' },
      { id: 'b', text: 'Frame' },
      { id: 'c', text: 'Packet' },
      { id: 'd', text: 'Segment' },
    ],
    correct: 'b',
    explanation: 'The Data Link layer (Layer 2) PDU is called a frame. Bits are Physical layer, packets are Network layer, and segments are Transport layer.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-9',
    type: 'multi-mcq',
    stem: 'Which protocols operate at the Transport layer? (Select all that apply)',
    options: [
      { id: 'a', text: 'TCP' },
      { id: 'b', text: 'IP' },
      { id: 'c', text: 'UDP' },
      { id: 'd', text: 'Ethernet' },
    ],
    correct: ['a', 'c'],
    explanation: 'TCP and UDP are Transport layer protocols. IP is Network layer, and Ethernet is Data Link layer.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-10',
    type: 'fill-blank',
    stem: 'The process of adding headers as data moves down the OSI model is called ___.',
    correct: 'encapsulation',
    explanation: 'Encapsulation adds headers (and sometimes trailers) at each layer as data moves from Application to Physical. The reverse process at the receiver is decapsulation.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  // --- IP Addressing (7 questions) ---
  {
    id: 'd1dq-11',
    type: 'single-mcq',
    stem: 'How many bits are in an IPv4 address?',
    options: [
      { id: 'a', text: '16' },
      { id: 'b', text: '32' },
      { id: 'c', text: '64' },
      { id: 'd', text: '128' },
    ],
    correct: 'b',
    explanation: 'IPv4 addresses are 32 bits long, typically written in dotted-decimal notation (e.g., 192.168.1.1). IPv6 addresses are 128 bits.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-12',
    type: 'true-false',
    stem: 'The address 192.168.1.1 is a public IP address.',
    correct: 'false',
    explanation: '192.168.x.x is a private (RFC 1918) address range. It is not routable on the public internet and is used for internal networks.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-13',
    type: 'single-mcq',
    stem: 'What is the default subnet mask for a Class C network?',
    options: [
      { id: 'a', text: '255.0.0.0' },
      { id: 'b', text: '255.255.0.0' },
      { id: 'c', text: '255.255.255.0' },
      { id: 'd', text: '255.255.255.255' },
    ],
    correct: 'c',
    explanation: 'Class C networks use 255.255.255.0 (/24) as the default subnet mask, providing 254 usable host addresses.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-14',
    type: 'multi-mcq',
    stem: 'Which of the following are private IP address ranges? (Select all that apply)',
    options: [
      { id: 'a', text: '10.0.0.0/8' },
      { id: 'b', text: '172.16.0.0/12' },
      { id: 'c', text: '192.168.0.0/16' },
      { id: 'd', text: '203.0.113.0/24' },
    ],
    correct: ['a', 'b', 'c'],
    explanation: 'RFC 1918 defines three private ranges: 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. 203.0.113.0/24 is a documentation/example range (RFC 5737).',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-15',
    type: 'fill-blank',
    stem: 'An IPv6 address is ___ bits long.',
    correct: '128',
    explanation: 'IPv6 addresses are 128 bits, providing vastly more addresses than IPv4\'s 32 bits. This was designed to solve IPv4 address exhaustion.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  // --- Subnetting (5 questions) ---
  {
    id: 'd1dq-16',
    type: 'single-mcq',
    stem: 'A /26 subnet mask provides how many usable host addresses?',
    options: [
      { id: 'a', text: '30' },
      { id: 'b', text: '32' },
      { id: 'c', text: '62' },
      { id: 'd', text: '64' },
    ],
    correct: 'c',
    explanation: 'A /26 has 6 host bits (32 - 26 = 6). 2^6 = 64 total addresses, minus 2 (network and broadcast) = 62 usable hosts.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-17',
    type: 'true-false',
    stem: 'The network address and broadcast address in a subnet can be assigned to hosts.',
    correct: 'false',
    explanation: 'The network address (all host bits = 0) identifies the subnet itself. The broadcast address (all host bits = 1) is used to reach all hosts. Neither can be assigned to individual hosts.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-18',
    type: 'single-mcq',
    stem: 'What is the CIDR notation for subnet mask 255.255.255.192?',
    options: [
      { id: 'a', text: '/24' },
      { id: 'b', text: '/25' },
      { id: 'c', text: '/26' },
      { id: 'd', text: '/27' },
    ],
    correct: 'c',
    explanation: '255.255.255.192 = 11111111.11111111.11111111.11000000 = 26 network bits = /26.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-19',
    type: 'fill-blank',
    stem: 'To create 4 subnets from a /24 network, you need to borrow ___ bits.',
    correct: '2',
    explanation: '2^2 = 4 subnets. Borrowing 2 bits from the host portion of a /24 gives you a /26, creating 4 subnets with 62 usable hosts each.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-20',
    type: 'multi-mcq',
    stem: 'Which statements about subnetting are correct? (Select all that apply)',
    options: [
      { id: 'a', text: 'Subnetting borrows bits from the host portion' },
      { id: 'b', text: 'Each subnet needs a network and broadcast address' },
      { id: 'c', text: 'A /30 subnet has 2 usable host addresses' },
      { id: 'd', text: 'Subnetting increases the total number of available IP addresses' },
    ],
    correct: ['a', 'b', 'c'],
    explanation: 'Subnetting borrows host bits to create more networks. Each subnet reserves 2 addresses (network + broadcast). A /30 has 2 host bits = 4 total - 2 = 2 usable hosts. Subnetting does not create more addresses; it organizes existing ones.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  // --- Wireless concepts (5 questions) ---
  {
    id: 'd1dq-21',
    type: 'single-mcq',
    stem: 'Which IEEE standard defines Wi-Fi?',
    options: [
      { id: 'a', text: '802.3' },
      { id: 'b', text: '802.11' },
      { id: 'c', text: '802.15' },
      { id: 'd', text: '802.16' },
    ],
    correct: 'b',
    explanation: 'IEEE 802.11 is the Wi-Fi standard. 802.3 is Ethernet, 802.15 is Bluetooth, and 802.16 is WiMAX.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-22',
    type: 'true-false',
    stem: 'Wireless is a dedicated media type where each device gets its own channel.',
    correct: 'false',
    explanation: 'Wireless is shared media. All devices on the same channel compete for airtime, unlike switched Ethernet where each port is its own collision domain.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-23',
    type: 'single-mcq',
    stem: 'What does a wireless access point (WAP) primarily do?',
    options: [
      { id: 'a', text: 'Route packets between networks' },
      { id: 'b', text: 'Bridge wireless clients to a wired network' },
      { id: 'c', text: 'Encrypt all network traffic' },
      { id: 'd', text: 'Assign IP addresses to clients' },
    ],
    correct: 'b',
    explanation: 'A WAP bridges wireless clients to a wired network, operating at Layers 1 and 2. It converts radio signals into Ethernet frames.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  // --- Virtualization basics (3 questions) ---
  {
    id: 'd1dq-24',
    type: 'single-mcq',
    stem: 'What is the primary benefit of network virtualization?',
    options: [
      { id: 'a', text: 'Faster cable speeds' },
      { id: 'b', text: 'Multiple logical networks on shared physical infrastructure' },
      { id: 'c', text: 'Eliminating the need for routers' },
      { id: 'd', text: 'Automatic IP address assignment' },
    ],
    correct: 'b',
    explanation: 'Network virtualization allows multiple logical networks to run on shared physical hardware, improving resource utilization and isolation.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  // --- Cloud intro (2 questions) ---
  {
    id: 'd1dq-25',
    type: 'true-false',
    stem: 'In IaaS (Infrastructure as a Service), the cloud provider manages the operating system.',
    correct: 'false',
    explanation: 'In IaaS, the provider manages the physical infrastructure (compute, storage, networking). The customer manages the OS, middleware, and applications. PaaS manages the OS; SaaS manages everything.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  // --- Additional mixed questions ---
  {
    id: 'd1dq-26',
    type: 'single-mcq',
    stem: 'Which layer of the OSI model handles encryption and compression?',
    options: [
      { id: 'a', text: 'Application' },
      { id: 'b', text: 'Presentation' },
      { id: 'c', text: 'Session' },
      { id: 'd', text: 'Transport' },
    ],
    correct: 'b',
    explanation: 'The Presentation layer (Layer 6) handles data translation, encryption, and compression. It ensures data from the Application layer is readable by the receiving system.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-27',
    type: 'multi-mcq',
    stem: 'Which of the following are valid IPv4 address classes? (Select all that apply)',
    options: [
      { id: 'a', text: 'Class A' },
      { id: 'b', text: 'Class B' },
      { id: 'c', text: 'Class E' },
      { id: 'd', text: 'Class F' },
    ],
    correct: ['a', 'b', 'c'],
    explanation: 'Valid IPv4 classes are A through E. Class A-C are for unicast, Class D is for multicast, and Class E is reserved for experimental use. Class F does not exist.',
    lessonId: 'd1-ip-addressing',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-28',
    type: 'fill-blank',
    stem: 'The ___ address is used to send data to all hosts on a network segment.',
    correct: 'broadcast',
    explanation: 'The broadcast address (all host bits set to 1) sends data to every host on the network segment. It cannot be assigned to an individual device.',
    lessonId: 'd1-subnetting-basics',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-29',
    type: 'single-mcq',
    stem: 'What type of fiber uses a laser and a thin core for long-distance transmission?',
    options: [
      { id: 'a', text: 'Multi-mode fiber' },
      { id: 'b', text: 'Single-mode fiber' },
      { id: 'c', text: 'Coaxial cable' },
      { id: 'd', text: 'Twisted pair' },
    ],
    correct: 'b',
    explanation: 'Single-mode fiber uses a laser and a thin core (about 9 microns) for long-distance transmission. Multi-mode uses LEDs and a wider core for shorter distances.',
    lessonId: 'd1-network-components',
    domainId: 'domain-1',
  },
  {
    id: 'd1dq-30',
    type: 'true-false',
    stem: 'TCP provides connectionless, unreliable delivery of data.',
    correct: 'false',
    explanation: 'TCP provides connection-oriented, reliable delivery with acknowledgment and retransmission. UDP provides connectionless, unreliable (but faster) delivery.',
    lessonId: 'd1-osi-model',
    domainId: 'domain-1',
  },
];
